name: Test Websocket Server

on:
  push:
    branches: [ main, develop ]
    paths: 
      - 'websocket-server/**'
      - '.github/workflows/test.yml'
  pull_request:
    branches: [ main, develop ]
    paths: 
      - 'websocket-server/**'
      - '.github/workflows/test.yml'

jobs:
  websocket-server-checks:
    name: Websocket Server Checks
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        node-version: [18.x, 20.x]

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        cache-dependency-path: websocket-server/package-lock.json

    - name: Install dependencies
      working-directory: ./websocket-server
      run: npm ci

    - name: Run security audit
      working-directory: ./websocket-server
      run: npm audit --audit-level=moderate

    - name: Build TypeScript
      working-directory: ./websocket-server
      run: npm run build

    - name: Check for TypeScript errors
      working-directory: ./websocket-server
      run: npx tsc --noEmit

    - name: Run tests
      working-directory: ./websocket-server
      run: npm run test:ci

    - name: Upload coverage reports
      if: matrix.node-version == '20.x'
      uses: codecov/codecov-action@v3
      with:
        directory: ./websocket-server/coverage
        flags: websocket-server
        name: websocket-server-coverage
        fail_ci_if_error: false