name: Test Websocket Server

on:
  push:
    branches: [ main, develop ]
    paths: 
      - 'websocket-server/**'
      - '.github/workflows/test.yml'
  pull_request:
    branches: [ main, develop ]
    paths: 
      - 'websocket-server/**'
      - '.github/workflows/test.yml'

jobs:
  test:
    name: Test (Node ${{ matrix.node-version }})
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        node-version: [18.x, 20.x]

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        cache-dependency-path: websocket-server/package-lock.json

    - name: Install dependencies
      working-directory: ./websocket-server
      run: npm ci

    - name: Run tests
      working-directory: ./websocket-server
      run: npm run test:ci

    - name: Upload coverage reports
      if: matrix.node-version == '20.x'
      uses: codecov/codecov-action@v3
      with:
        directory: ./websocket-server/coverage
        flags: websocket-server
        name: websocket-server-coverage
        fail_ci_if_error: false

  lint:
    name: Lint & Build
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20.x'
        cache: 'npm'
        cache-dependency-path: websocket-server/package-lock.json

    - name: Install dependencies
      working-directory: ./websocket-server
      run: npm ci

    - name: Build TypeScript
      working-directory: ./websocket-server
      run: npm run build

    - name: Check for TypeScript errors
      working-directory: ./websocket-server
      run: npx tsc --noEmit

  security:
    name: Security Audit
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20.x'
        cache: 'npm'
        cache-dependency-path: websocket-server/package-lock.json

    - name: Install dependencies
      working-directory: ./websocket-server
      run: npm ci

    - name: Run security audit
      working-directory: ./websocket-server
      run: npm audit --audit-level=moderate

  # Summary job that all checks must pass
  websocket-server-checks:
    name: All Websocket Server Checks
    runs-on: ubuntu-latest
    needs: [test, lint, security]
    if: always()
    
    steps:
    - name: Check all jobs
      run: |
        if [[ "${{ needs.test.result }}" == "success" && 
              "${{ needs.lint.result }}" == "success" && 
              "${{ needs.security.result }}" == "success" ]]; then
          echo "✅ All checks passed!"
          exit 0
        else
          echo "❌ Some checks failed:"
          echo "- Tests: ${{ needs.test.result }}"
          echo "- Lint: ${{ needs.lint.result }}"
          echo "- Security: ${{ needs.security.result }}"
          exit 1
        fi